# PhotoPort Site Styling Configuration
# This file controls the visual appearance and branding of the PhotoPort site

# Site branding
site_name: "Guy LeBlanc"
site_subheader: "Travel photography"
page_title: "Guy LeBlanc - Travel Photography"
site_logo_path: "/assets/logo.svg"
site_default_gallery: "responsive"

# Color scheme - Monochromatic palette inspired by professional photography portfolios
colors:
  background_color: "#ffffff"
  text_color: "#1a1a1a"
  link_color: "#404040"
  hover_link_color: "#000000"
  accent_color: "#f5f5f5"
  header_background_color: "#ffffff"
  secondary_text_color: "#666666"
  border_color: "#e5e5e5"

# Typography - Clean, professional fonts
typography:
  primary_font: "'Lato', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
  heading_font: "'Lato', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
  font_weight_normal: "400"
  font_weight_medium: "500"
  font_weight_bold: "700"
  
  # Header typography settings
  site_name_font_size: "2rem"  # text-xl equivalent
  site_name_font_weight: "700"    # font-bold equivalent
  site_name_letter_spacing: ".2px"  # Letter spacing for site name (e.g., "0.1em", "2px", "normal")
  site_subheader_font_size: "1rem"  # text-sm equivalent
  site_subheader_font_weight: "400"     # normal weight
  site_subheader_letter_spacing: "2.4px"  # Letter spacing for subheader (e.g., "0.05em", "1px", "normal")
  
# Layout settings
layout:
  max_content_width: "1485px"
  gallery_columns: "3"
  image_aspect_ratio: "4:3"
  header_top_padding: "2rem"  # Additional spacing from top of page to match joshtaylor.photo

# Footer settings
footer:
  show_photoport_credit: true  # Show "Created with PhotoPort" link in footer
